server {
    listen 80;
    root /usr/share/nginx/html;
    index index.php index.html;

    # timeout
    proxy_connect_timeout 60s;
    proxy_read_timeout 60s;

    location ~ \.php$ {
        fastcgi_pass process-manager:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /api/ {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr
    }
    
    location ~* \.(jpg|jpeg|png|css|js)$ {
        expires 30d;
    }
}